---
title: "final_hunter_ross"
format: html
---

https://github.com/Hunter-Ross-3/ENVS-193DS_spring-2025_final

```{r - packages}
#| message: false
#loading packages

library(tidyverse)
library(janitor)
library(here)
library(flextable)
library(readxl)

# read in data
sst <- read.csv(here("data/SST_update2023.csv"))
```

# Problem 1: Research writing 

### a. Transparent statistical methods

In part 1 the researchers used a correlation test because they are looking at the relationship between two continuous variables. In part 2 the researches used a ANOVA test because they are comparing different means. 

### b. More information needed

Another test my coworker could run in a linear regression analysis. This test would give the rate of change in nitrogen load from the headwaters to downstream. Also my coworker could include more of the details in their description. For example we are told the p-vales but not the sample size, standard deviation, or mean all of which would give up a better understanding of the results.  

### c. Suggestions for rewriting

Nitrogen load increases with distance from the headwaters, suggesting downstream accumulation from runoff. It also differed by source type, indicating that multiple sources contribute more than others. TO better interpret these patterns, we need better summary statistics. (Linear regression: slope = [slope], r² = [r²], p = 0.03, α = 0.05; ANOVA: F = [F], df = [df], p = 0.02, α = 0.05; descriptive stats not yet reported)

# Problem 2. Data Visualization

### a. Cleaning and summarizing



### b. Data visualization



# Problem 3. Data analysis

### a. Response variable



### b. Purpose of study



### c. Difference in "seasons"



### d. Table of models



### e. Run the models



### f. Check the diagnostics



### g. Select the best model



### h. Visualize the model predictions



### i. Write a caption for figure



### j. Calculate model predictions



### k. Interpret results



# Problem 4. Affective and exploratory visualizations

### a. Comparing visualizations



### b. Sharing your affective visualization




















